syntax = "proto3";
option cc_enable_arenas = true;
option csharp_namespace = "DonkeyCrew.Oasis.Backend.Web.Protos";
package MistProto;

message BackendApiQueuedConnectionRequest
{
	int64 queue_id = 1;
}

message BackendApiQueuedConnectionResponse
{
	int64 queue_id = 1;
	int32 queue_position = 2;
	string connection_string = 3;
	int64 waiting_time = 4;
	int64 character_id = 5;
	int32 direction = 6;
	bool tile_online = 7;
	int64 tile_id = 8;
	int64 realm_id = 9;
	int64 offmap_character_id = 10;
}

message BackendApiConnectionResponse 
{
	// Set to a non-default value if there is a queue.
	int64 queue_id = 1;
	// Set if there is no queue.
	string connection_string = 2;
}